# Generated by Django 5.2.6 on 2025-09-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_financial_info_results_delete_todoitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial_info',
            name='company',
            field=models.CharField(default=None),
        ),
    ]
